language: python
python:
  - "2.6"
  - "2.7"
install: "pip install -r requirements.txt"
script: nosetests
#script: perl ./app/test.pl
#language: python
#python: 
#  - "3.2"
#install: "python get-pip.py"   
#install: ./djangosetup.sh
