language: bash

#install: "curl -kL https://bootstrap.pypa.io/get-pip.py | python"
install: pip install -r ref_manager/requirements.txt

#script: perl ./app/test.pl  
script: 
  - pip --help
  - curl --help
  - python --version 
#  - python --version 
  - bash djangosetup.sh
