language: bash
script: perl ./app/test.pl
deploy:
  - provider: s3
  - provider: codedeploy
    access_key_id: "YOUR AWS ACCESS KEY"
    secret_access_key: "YOUR AWS SECRET KEY"
    bucket: "S3 Bucket"
    on: 
      branch: masaki


